//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPUMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:30")]
        public global::System.TimeSpan How_Frequently_To_Check {
            get {
                return ((global::System.TimeSpan)(this["How_Frequently_To_Check"]));
            }
            set {
                this["How_Frequently_To_Check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int CPU_Threshold {
            get {
                return ((int)(this["CPU_Threshold"]));
            }
            set {
                this["CPU_Threshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:01:00")]
        public global::System.TimeSpan How_Long_To_Wait_Before_Warning_For_CPU {
            get {
                return ((global::System.TimeSpan)(this["How_Long_To_Wait_Before_Warning_For_CPU"]));
            }
            set {
                this["How_Long_To_Wait_Before_Warning_For_CPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan How_Long_To_Wait_Before_Kill_Notice_For_CPU {
            get {
                return ((global::System.TimeSpan)(this["How_Long_To_Wait_Before_Kill_Notice_For_CPU"]));
            }
            set {
                this["How_Long_To_Wait_Before_Kill_Notice_For_CPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200000000")]
        public long Memory_Threshold_Bytes {
            get {
                return ((long)(this["Memory_Threshold_Bytes"]));
            }
            set {
                this["Memory_Threshold_Bytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:01:00")]
        public global::System.TimeSpan How_Long_To_Wait_Before_Warning_For_Memory {
            get {
                return ((global::System.TimeSpan)(this["How_Long_To_Wait_Before_Warning_For_Memory"]));
            }
            set {
                this["How_Long_To_Wait_Before_Warning_For_Memory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan How_Long_To_Wait_Before_Kill_Notice_For_Memory {
            get {
                return ((global::System.TimeSpan)(this["How_Long_To_Wait_Before_Kill_Notice_For_Memory"]));
            }
            set {
                this["How_Long_To_Wait_Before_Kill_Notice_For_Memory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan Default_Postpone_Time {
            get {
                return ((global::System.TimeSpan)(this["Default_Postpone_Time"]));
            }
            set {
                this["Default_Postpone_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:30")]
        public global::System.TimeSpan How_Long_To_Wait_Before_Killing_Process_If_Normal_Close_Does_Not_Work {
            get {
                return ((global::System.TimeSpan)(this["How_Long_To_Wait_Before_Killing_Process_If_Normal_Close_Does_Not_Work"]));
            }
            set {
                this["How_Long_To_Wait_Before_Killing_Process_If_Normal_Close_Does_Not_Work"] = value;
            }
        }
    }
}
